//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlStorage {
	
	
	public partial class AddMovie {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
		
		protected System.Web.UI.WebControls.TextBox TitleTB;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredText;
		
		protected System.Web.UI.WebControls.DropDownList DDLYear;
		
		protected System.Web.UI.WebControls.TextBox DurationTB;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredDuration;
		
		protected System.Web.UI.WebControls.RangeValidator RangeDuration;
		
		protected System.Web.UI.WebControls.TextBox GenreTB;
		
		protected System.Web.UI.WebControls.TextBox DirectorTB;
		
		protected System.Web.UI.WebControls.TextBox Actor1TB;
		
		protected System.Web.UI.WebControls.TextBox Actor2TB;
		
		protected System.Web.UI.WebControls.FileUpload PosterFU;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredPoster;
		
		protected System.Web.UI.WebControls.Button BAddMovie;
	}
}
