//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlStorage {
	
	
	public partial class DeleteMovie {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Literal TitleL;
		
		protected System.Web.UI.WebControls.Literal YearL;
		
		protected System.Web.UI.WebControls.Button BDelete;
		
		protected System.Web.UI.WebControls.Button BCancel;
	}
}
